Zapateria/Controllers/InicioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Zapateria.Models;
using Zapateria.DAO;

namespace Zapateria.Controllers
{
    public class InicioController : Controller
    {
        // GET: Inicio
        public ActionResult vistaPrincipal()
        {
            return View("vistaPrincipal");
        }
        public ActionResult Login()
        {
           
            return View("Login");
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult login_(UsuarioModel usuario)
        {
            if (!string.IsNullOrWhiteSpace(usuario.correo) &&
        !string.IsNullOrWhiteSpace(usuario.contra))
            {
                LoginDAO login = new LoginDAO();
                
                UsuarioModel usu = login.verificar(usuario);
                if (usu != null)
                {

                    Session["usuario"] = usu;



                   
                            // administrador 1

                            return Redirect("~/Backend/GuardarZapato");
                        
                    // return Redirect("~/BackendAdmin/login");
                }
               

                //  Response.Write("<script>alert('Correo o contraseña incorrecta ')</script>");

                return Redirect("~/Inicio/Login");
            }
            else
            {
                ViewBag.Result = null;
                return View("Login");
            }
        }

        public ActionResult Mision()
        {
           
            return View("Mision");
        }
        public ActionResult Vision()
        {

            return View("vision");
        }
        public ActionResult Contacto()
        {

            return View("Contacto");
        }
    }
}

Zapateria/Views/Inicio/Contacto.cshtml
@{
    ViewBag.Title = "Contacto";
    Layout = "~/Views/Shared/_Front.cshtml";
}

<!-- Start Banner Area -->
<section class="banner-area organic-breadcrumb">
    <div class="container">
        <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
            <div class="col-first">
                <h1>Contacto</h1>
                <nav class="d-flex align-items-center">
                    <a href="index.html">Inicio<span class="lnr lnr-arrow-right"></span></a>
                    <a href="category.html">Contacto</a>
                </nav>
            </div>
        </div>
    </div>
</section>
<!-- End Banner Area -->
<section class="contact_area section_gap_bottom">
    <div class="container">
        <div id="mapBox" class="mapBox" data-lat="40.701083" data-lon="-74.1522848" data-zoom="13" data-info="PO Box CT16122 Collins Street West, Victoria 8007, Australia."
             data-mlat="40.701083" data-mlon="-74.1522848">
        </div>
        <div class="row">
            <div class="col-lg-3">
                <div class="contact_info">
                    <div class="info_item">
                        <i class="lnr lnr-home"></i>
                        <h6>California, United States</h6>
                        <p>Santa monica bullevard</p>
                    </div>
                    <div class="info_item">
                        <i class="lnr lnr-phone-handset"></i>
                        <h6><a href="#">00 (440) 9865 562</a></h6>
                        <p>Mon to Fri 9am to 6 pm</p>
                    </div>
                    <div class="info_item">
                        <i class="lnr lnr-envelope"></i>
                        <h6><a href="#">support@colorlib.com</a></h6>
                        <p>Send us your query anytime!</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-9">
                <form class="row contact_form" action="contact_process.php" method="post" id="contactForm" novalidate="novalidate">
                    <div class="col-md-6">
                        <div class="form-group">
                            <input type="text" class="form-control" id="name" name="name" placeholder="Enter your name" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter your name'">
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-control" id="email" name="email" placeholder="Enter email address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" id="subject" name="subject" placeholder="Enter Subject" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Subject'">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <textarea class="form-control" name="message" id="message" rows="1" placeholder="Enter Message" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Message'"></textarea>
                        </div>
                    </div>
                    <div class="col-md-12 text-right">
                        <button type="submit" value="submit" class="primary-btn">Send Message</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

Zapateria/Views/Inicio/Login.cshtml
@model Zapateria.Models.UsuarioModel
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Front.cshtml";
}

<!-- Start Banner Area -->
<section class="banner-area organic-breadcrumb">
    <div class="container">
        <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
            <div class="col-first">
                <h1>Login/Register</h1>
                <nav class="d-flex align-items-center">
                    <a href="index.html">Home<span class="lnr lnr-arrow-right"></span></a>
                    <a href="category.html">Login/Register</a>
                </nav>
            </div>
        </div>
    </div>
</section>
<!-- End Banner Area -->
<!--================Login Box Area =================-->
<section class="login_box_area section_gap">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="login_box_img">
                    <img class="img-fluid" src="~/karma/img/login.jpg" alt="">
                    <div class="hover">
                        <h4>New to our website?</h4>
                        <p>There are advances being made in science and technology everyday, and a good example of this is the</p>
                        <a class="primary-btn" href="registration.html">Create an Account</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="login_form_inner">
                    <h3>Log in to enter</h3>

                    @using (Html.BeginForm("login_", "Inicio"))
                    {
                        @Html.AntiForgeryToken()
                        <form class="row login_form" action="contact_process.php" method="post" id="contactForm" novalidate="novalidate">
                            <div class="col-md-12 form-group">
                                @Html.EditorFor(model => model.correo, new { htmlAttributes = new { @class = "form-control" } })
                                @*<input type="text" class="form-control" id="name" name="name" placeholder="Username" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Username'">*@
                            </div>
                            <div class="col-md-12 form-group">
                                @Html.EditorFor(model => model.contra, new { htmlAttributes = new { @class = "form-control" } })
                                @*<input type="text" class="form-control" id="name" name="name" placeholder="Password" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Password'">*@
                            </div>
                            <div class="col-md-12 form-group">
                                <div class="creat_account">
                                    <input type="checkbox" id="f-option2" name="selector">
                                    <label for="f-option2">Keep me logged in</label>
                                </div>
                            </div>
                            <div class="col-md-12 form-group">
                                <button type="submit" value="submit" class="primary-btn">Log In</button>
                                <a href="#">Forgot Password?</a>
                            </div>
                        </form>
                    }
                </div>
            </div>
        </div>
    </div>
</section>
<!--================End Login Box Area =================-->

Zapateria/Views/Inicio/Mision.cshtml
@{
    ViewBag.Title = "Mision";
    Layout = "~/Views/Shared/_Front.cshtml";
}
<!-- Start Banner Area -->
<section class="banner-area organic-breadcrumb">
    <div class="container">
        <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
            <div class="col-first">
                <h1>Misión</h1>
                <nav class="d-flex align-items-center">
                    <a href="index.html">Inicio<span class="lnr lnr-arrow-right"></span></a>
                    <a href="category.html">Misión</a>
                </nav>
            </div>
        </div>
    </div>
</section>
<!-- End Banner Area -->

Zapateria/Views/Inicio/Vision.cshtml
@{
    ViewBag.Title = "Vision";
    Layout = "~/Views/Shared/_Front.cshtml";
}

<!-- Start Banner Area -->
<section class="banner-area organic-breadcrumb">
    <div class="container">
        <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
            <div class="col-first">
                <h1>Visión</h1>
                <nav class="d-flex align-items-center">
                    <a href="index.html">Inicio<span class="lnr lnr-arrow-right"></span></a>
                    <a href="category.html">Visión</a>
                </nav>
            </div>
        </div>
    </div>
</section>
<!-- End Banner Area -->

Zapateria/Views/Inicio/vistaPrincipal.cshtml
@{
    ViewBag.Title = "vistaPrincipal";
    Layout = "~/Views/Shared/_Front.cshtml";
}
<section class="banner-area">
    <div class="container">
        <div class="row fullscreen align-items-center justify-content-start">
            <div class="col-lg-12">
                <div class="active-banner-slider owl-carousel">
                    <!-- single-slide -->
                    <div class="row single-slide align-items-center d-flex">
                        <div class="col-lg-5 col-md-6">
                            <div class="banner-content">
                                <h1>Nike New <br>Collection!</h1>
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.
                                </p>
                                <div class="add-bag d-flex align-items-center">
                                    <a class="add-btn" href=""><span class="lnr lnr-cross"></span></a>
                                    <span class="add-text text-uppercase">Add to Bag</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-7">
                            <div class="banner-img">
                                <img class="img-fluid" src="../karma/img/banner/banner-img.png" alt="">
                            </div>
                        </div>
                    </div>
                    <!-- single-slide -->
                    <div class="row single-slide">
                        <div class="col-lg-5">
                            <div class="banner-content">
                                <h1>Nike New <br>Collection!</h1>
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.
                                </p>
                                <div class="add-bag d-flex align-items-center">
                                    <a class="add-btn" href=""><span class="lnr lnr-cross"></span></a>
                                    <span class="add-text text-uppercase">Add to Bag</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-7">
                            <div class="banner-img">
                                <img class="img-fluid" src="../karma/img/banner/banner-img.png" alt="">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--final encabezado-->
<div class="row justify-content-center align-items-center">
    <div class="col-lg-6 no-padding exclusive-left">
        <div class="row clock_sec clockdiv" id="clockdiv">
            <div class="col-lg-12">
                <h1>Exclusive Hot Deal Ends Soon!</h1>
                <p>Who are in extremely love with eco friendly system.</p>
            </div>
            <div class="col-lg-12">
                <div class="row clock-wrap">
                    <div class="col clockinner1 clockinner">
                        <h1 class="days">150</h1>
                        <span class="smalltext">Days</span>
                    </div>
                    <div class="col clockinner clockinner1">
                        <h1 class="hours">23</h1>
                        <span class="smalltext">Hours</span>
                    </div>
                    <div class="col clockinner clockinner1">
                        <h1 class="minutes">47</h1>
                        <span class="smalltext">Mins</span>
                    </div>
                    <div class="col clockinner clockinner1">
                        <h1 class="seconds">59</h1>
                        <span class="smalltext">Secs</span>
                    </div>
                </div>
            </div>
        </div>
        <a href="" class="primary-btn">Shop Now</a>
    </div>
    <div class="col-lg-6 no-padding exclusive-right">
        <div class="active-exclusive-product-slider">
            <!-- single exclusive carousel -->
            <div class="single-exclusive-slider">
                <img class="img-fluid" src="img/product/e-p1.png" alt="">
                <div class="product-details">
                    <div class="price">
                        <h6>$150.00</h6>
                        <h6 class="l-through">$210.00</h6>
                    </div>
                    <h4>
                        addidas New Hammer sole
                        for Sports person
                    </h4>
                    <div class="add-bag d-flex align-items-center justify-content-center">
                        <a class="add-btn" href=""><span class="ti-bag"></span></a>
                        <span class="add-text text-uppercase">Add to Bag</span>
                    </div>
                </div>
            </div>
            <!-- single exclusive carousel -->
            <div class="single-exclusive-slider">
                <img class="img-fluid" src="img/product/e-p1.png" alt="">
                <div class="product-details">
                    <div class="price">
                        <h6>$150.00</h6>
                        <h6 class="l-through">$210.00</h6>
                    </div>
                    <h4>
                        addidas New Hammer sole
                        for Sports person
                    </h4>
                    <div class="add-bag d-flex align-items-center justify-content-center">
                        <a class="add-btn" href=""><span class="ti-bag"></span></a>
                        <span class="add-text text-uppercase">Add to Bag</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>