Zapateria/Controllers/BackendController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Zapateria.Models;
using Zapateria.DAO;
using System.IO;

namespace Zapateria.Controllers
{
    public class BackendController : Controller
    {
        // GET: Backend
        public ActionResult InicioBackend()
        {
            if (Session["usuario"] != null)
            {
                ViewBag.vista = (UsuarioModel)Session["usuario"];
                return View();
            }
            return View();
        }

        public ActionResult GuardarZapato()
        {
            if (Session["usuario"] != null)
            {
                ViewBag.vista = (UsuarioModel)Session["usuario"];
                return View();
            }
            return View();
        }
        public ActionResult saveZapato(Zapatos zapats)
        {
            string filename;
            string extencion;

            ZapaDAL obj = new ZapaDAL();
            filename = Path.GetFileNameWithoutExtension(zapats.ImageFile.FileName);
            extencion = Path.GetExtension(zapats.ImageFile.FileName);
            filename = filename + DateTime.Now.ToString("yymmssfff") + extencion;
            // cursos.id_vendedor = ViewBag.vista.id;
            zapats.Imagen = "~/imagenes/" + filename;
            filename = Path.Combine(Server.MapPath("~/imagenes/"), filename);
            zapats.ImageFile.SaveAs(filename);





            int i = obj.agregar(zapats);
            if (Session["usuario"] != null)
            {
                ViewBag.vista = (UsuarioModel)Session["usuario"];
                return View("GuardarZapato");
            }
            return View("GuardarZapato");
        }
        public ActionResult Create()
        {
            if (Session["usuario"] != null)
            {
                ViewBag.vista = (UsuarioModel)Session["usuario"];
                return View();

            }
            return View();
        }
        [HttpPost]
        public ActionResult Create(Zapatos collection)
        {
            try
            {
                // TODO: Add insert logic here

                if (ModelState.IsValid)
                {
                    string filename;
                    string extencion;

                    filename = Path.GetFileNameWithoutExtension(collection.ImageFile.FileName);
                    extencion = Path.GetExtension(collection.ImageFile.FileName);
                    filename = filename + DateTime.Now.ToString("yymmssfff") + extencion;
                    // cursos.id_vendedor = ViewBag.vista.id;
                    collection.Imagen = "~/imagenes/" + filename;
                    filename = Path.Combine(Server.MapPath("~/imagenes/"), filename);
                    collection.ImageFile.SaveAs(filename);

                    zapatosDAL.AgregarZapato(collection);
                    if (Session["usuario"] != null)
                    {
                        ViewBag.vista = (UsuarioModel)Session["usuario"];
                        return RedirectToAction("Index");

                    }
                    return View("Index");
                }
                else
                {
                    if (Session["usuario"] != null)
                {
                    ViewBag.vista = (UsuarioModel)Session["usuario"];
                    return View();

                }
                return View();
                }

            }
            catch(Exception e)
            {
                return View(e.Message);
            }
        }
        public ActionResult Edit(int id)
        {

             Zapatos o = zapatosDAL.ObtenerDatosZapatos(id);
            if (Session["usuario"] != null)
            {
                ViewBag.vista = (UsuarioModel)Session["usuario"];

                return View(o);
            }
            
           
            return View();
        }
         ZapatosDAL zapatosDAL = new ZapatosDAL();
        public ActionResult Index()
        {
            ZapatosDAL zapatosDAL = new ZapatosDAL();
            List<Zapatos> lstempleados = new List<Zapatos>();
            lstempleados = zapatosDAL.ListarZapatos().ToList();
            if (Session["usuario"] != null)
            {
                ViewBag.vista = (UsuarioModel)Session["usuario"];
                return View(lstempleados);
                
            }
            return View();

        }
        public ActionResult Details(int id)
        {
            Zapatos Oempledos = zapatosDAL.ObtenerDatosZapatos(id);
            if (Session["usuario"] != null)
            {
                ViewBag.vista = (UsuarioModel)Session["usuario"];
                return View(Oempledos);

            }
          
            return View();

        }
        public ActionResult Delete(int id)
        {
           Zapatos o = zapatosDAL.ObtenerDatosZapatos(id);
            if (Session["usuario"] != null)
            {
                ViewBag.vista = (UsuarioModel)Session["usuario"];
                return View(o);

            }
           
            return View();
        }

        // POST: Empleado/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Zapatos collection)
        {
            try
            {
                // TODO: Add delete logic here
                zapatosDAL.BorrarZapato(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult cerrar_sesion()
        {
            Session.Remove("usuario");
            Session.Abandon();
            return Redirect("~/Inicio/vistaPrincipal");
        }
        [HttpPost]
        public ActionResult Edit(int id, Zapatos collection)
        {
            try
            {
                // TODO: Add update logic here

                if (ModelState.IsValid)
                {
                    string filename;
                    string extencion;
                    if (collection.ImageFile!=null )
                    {
                        filename = Path.GetFileNameWithoutExtension(collection.ImageFile.FileName);
                        extencion = Path.GetExtension(collection.ImageFile.FileName);
                        filename = filename + DateTime.Now.ToString("yymmssfff") + extencion;
                        // cursos.id_vendedor = ViewBag.vista.id;
                        collection.Imagen = "~/imagenes/" + filename;
                        filename = Path.Combine(Server.MapPath("~/imagenes/"), filename);
                        collection.ImageFile.SaveAs(filename);
                    }
                   

                    zapatosDAL.ModificarZapatos(collection);
                    if (Session["usuario"] != null)
                    {
                        ViewBag.vista = (UsuarioModel)Session["usuario"];

                        return RedirectToAction("Index");
                    }
                   
                }
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                
                return View(e.Message);
            }
        }
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult guardar_curso(CursosBO cursos)
        //{
        //    if (Session["usuario"] != null)
        //    {
        //        CursosDAO curso = new CursosDAO();
        //        string filename;
        //        string extencion;
        //        usuarioDAO vendedores = new usuarioDAO();

        //        ViewBag.vendedores = vendedores.mandar_lista_vendedores();
        //        ViewBag.vista = (usuarioBO)Session["usuario"];
        //        if (!string.IsNullOrWhiteSpace(cursos.nombre_curso) &&
        //!string.IsNullOrWhiteSpace(cursos.duracion) && !string.IsNullOrWhiteSpace(cursos.precio.ToString()) && !string.IsNullOrWhiteSpace(cursos.fecha_curso.ToString()) && cursos.id_vendedor > 0 && cursos.tipo_cursos != 0 && !string.IsNullOrWhiteSpace(cursos.descripcion))
        //        {
        //            if (cursos.id_cursos > 0)
        //            {
        //                CursosBO s = new CursosBO();
        //                if (cursos.imagen_http != null && cursos.imagen_http.ContentLength > 0)
        //                {
        //                    filename = Path.GetFileNameWithoutExtension(cursos.imagen_http.FileName);
        //                    extencion = Path.GetExtension(cursos.imagen_http.FileName);
        //                    filename = filename + DateTime.Now.ToString("yymmssfff") + extencion;
        //                    // cursos.id_vendedor = ViewBag.vista.id;
        //                    cursos.foto_curso = "~/imagenes/" + filename;
        //                    filename = Path.Combine(Server.MapPath("~/imagenes/"), filename);
        //                    cursos.imagen_http.SaveAs(filename);
        //                    curso.editar_curso(cursos);
        //                    ModelState.Clear();
        //                    ViewBag.resul = 2;

        //                }
        //                else
        //                {

        //                    curso.editar_curso(cursos);
        //                    ModelState.Clear();
        //                    ViewBag.resul = 2;

        //                }
        //            }
        //            else
        //            {
        //                filename = Path.GetFileNameWithoutExtension(cursos.imagen_http.FileName);
        //                extencion = Path.GetExtension(cursos.imagen_http.FileName);
        //                filename = filename + DateTime.Now.ToString("yymmssfff") + extencion;
        //                // cursos.id_vendedor = ViewBag.vista.id;
        //                cursos.foto_curso = "~/imagenes/" + filename;
        //                filename = Path.Combine(Server.MapPath("~/imagenes/"), filename);

Zapateria/Views/Backend/Create.cshtml
@model Zapateria.Models.Zapatos

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_BackendLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Backend", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Zapatos</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Contenido, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Contenido, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Contenido, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Precio, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <img class="img-fluid img-responsive" src="~/karma/img/category/c1.jpg" id="img1" name="img1" style="height:300px !important;width:300px !important" />

        </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Imagen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="ImageFile" name="ImageFile" required="required" class="form-control ">
                @*@Html.EditorFor(model => model.Imagen, new { htmlAttributes = new { @class = "form-control" } })*@
                @*@Html.ValidationMessageFor(model => model.Imagen, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>

    <script>
        function mostrarfoto(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#img1').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#ImageFile").change(function () {
            mostrarfoto(this);
        });
    </script>

Zapateria/Views/Backend/Delete.cshtml
@model Zapateria.Models.Zapatos

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_BackendLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Zapatos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contenido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contenido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Precio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Imagen)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Zapateria/Views/Backend/Details.cshtml
@model Zapateria.Models.Zapatos

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_BackendLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Zapatos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contenido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contenido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Precio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>

        <dd>
            @{
                string path = Server.MapPath(Model.Imagen);
                byte[] imageByteData = System.IO.File.ReadAllBytes(path);
                string imageBase64Data = Convert.ToBase64String(imageByteData);
                string imageDataURL = string.Format("data:image/png;base64,{0}", imageBase64Data);
                ViewBag.ImageData = imageDataURL;
            }
            <img src="@ViewBag.ImageData" height="200px" width="200px" class="img-fluid" alt="Responsive image">
            @*<img src="@Html.DisplayFor(model => model.Imagen)" class="img-fluid" alt="Responsive image">*@

        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Zapateria/Views/Backend/Edit.cshtml
@model Zapateria.Models.Zapatos

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_BackendLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Backend", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Zapatos</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID)

    <div class="form-group">
        @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Contenido, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Contenido, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Contenido, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Precio, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
        </div>
    </div>
    @{ 
        string path = Server.MapPath(Model.Imagen);
        byte[] imageByteData = System.IO.File.ReadAllBytes(path);
        string imageBase64Data = Convert.ToBase64String(imageByteData);
        string imageDataURL = string.Format("data:image/png;base64,{0}", imageBase64Data);
        ViewBag.ImageData = imageDataURL;
    }
    <div class="col-md-10">
        <img class="img-fluid img-responsive" src="@ViewBag.ImageData" id="img1" name="img1" style="height:300px !important;width:300px !important" />

    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Imagen, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" id="ImageFile" name="ImageFile" class="form-control ">
            @Html.HiddenFor(model => model.Imagen, new { htmlAttributes = new { @class = "form-control" } })

        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Zapateria/Views/Backend/GuardarZapato.cshtml
@model Zapateria.Models.Zapatos

    @{
        ViewBag.Title = "GuardarZapato";
        Layout = "~/Views/Shared/_BackendLayout.cshtml";
    }

<div class="x_panel">
    <div class="x_title">
        <h2>Form Design <small>different form elements</small></h2>
        <ul class="nav navbar-right panel_toolbox">
            <li>
                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                <ul class="dropdown-menu" role="menu">
                    <li>
                        <a href="#">Settings 1</a>
                    </li>
                    <li>
                        <a href="#">Settings 2</a>
                    </li>
                </ul>
            </li>
            <li>
                <a class="close-link"><i class="fa fa-close"></i></a>
            </li>
        </ul>
        <div class="clearfix"></div>
    </div>
    @using (Html.BeginForm("saveZapato", "Backend", FormMethod.Post, new { @class = "form-horizontal form-label-left" , enctype = "multipart/form-data" }))
    {
                @Html.AntiForgeryToken()

                <div class="x_content">
            <br>

            <form id="demo-form2" data-parsley-validate="" class="form-horizontal form-label-left" novalidate="">

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
                        Titulo <span class="required">*</span>
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control col-md-7 col-xs-12" } })

                        @*<input type="text" id="first-name" required="required" class="form-control col-md-7 col-xs-12">*@
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">
                        Contenido <span class="required">*</span>
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        @Html.EditorFor(model => model.Contenido, new { htmlAttributes = new { @class = "form-control col-md-7 col-xs-12" } })

                        @*<input type="text" id="last-name" name="last-name" required="required" class="form-control col-md-7 col-xs-12">*@
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">
                        Precio <span class="required">*</span>
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control col-md-7 col-xs-12" } })

                        @*<input type="text" id="last-name" name="last-name" required="required" class="form-control col-md-7 col-xs-12">*@
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">
                        Imagen <span class="required">*</span>
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                    
                        <input type="file" id="ImageFile" name="ImageFile" required="required" class="form-control col-md-7 col-xs-12">
                    </div>
                </div>



                <div class="ln_solid"></div>
                <div class="form-group">
                    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">

                        <button type="submit" class="btn btn-success">Save</button>
                    </div>
                </div>

            </form>


        </div>
                   }

    </div>

Zapateria/Views/Backend/Index.cshtml
@model IEnumerable<Zapateria.Models.Zapatos>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_BackendLayout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Titulo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Contenido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Precio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Imagen)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    string path = Server.MapPath(item.Imagen);
    byte[] imageByteData = System.IO.File.ReadAllBytes(path);
    string imageBase64Data = Convert.ToBase64String(imageByteData);
    string imageDataURL = string.Format("data:image/png;base64,{0}", imageBase64Data);
    ViewBag.ImageData = imageDataURL;
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Titulo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Contenido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Precio)
        </td>
        <td>
            <img src="@ViewBag.ImageData" height="200px" width="200px" class="img-fluid" alt="Responsive image">
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

Zapateria/Views/Backend/InicioBackend.cshtml
@{
    ViewBag.Title = "InicioBackend";
    Layout = "~/Views/Shared/_BackendLayout.cshtml";
}

<h2>InicioBackend</h2>